version: "3.9"

services:
  mongodb:
    image: mongo:7
    container_name: ctf-mongodb

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: ctf_platform

    volumes:
      - mongodb_data:/data/db

    networks:
      - ctf-network

  redis:
    image: redis:7-alpine
    container_name: ctf-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    networks:
      - ctf-network

volumes:
  mongodb_data:
  redis_data:

networks:
  ctf-network:
    driver: bridge

    